name: Merge All PRs Java Build

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  merge_all_prs_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merged branch
        uses: actions/checkout@v3
        with:
          ref: merged
          fetch-depth: 0
          persist-credentials: true

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get open PR branches and numbers
        id: prlist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh pr list --state open --json number,headRefName > prs.json
          jq -r '.[] | "\(.headRefName) \(.number)"' prs.json > pr_branches.txt

      - name: Merge all PRs into merged
        run: |
          while read branch pr_number; do
            echo "Merging PR #$pr_number ($branch)"
            git fetch origin $branch
            if ! git merge --no-ff --no-edit origin/$branch; then
              echo "::error::Conflict merging PR #$pr_number ($branch)"
              echo "PR #$pr_number: ❌ Merge conflict when combining all PRs." >> pr_results.txt
              exit 1
            else
              echo "PR #$pr_number: ✅ Merged successfully into combined build." >> pr_results.txt
            fi
          done < pr_branches.txt

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Gradle Build
        run: ./gradlew clean build

      - name: Upload build artifacts (JARs, reports)
        uses: actions/upload-artifact@v4
        with:
          name: gradle-artifacts
          path: |
            build/libs/
            build/reports/
          if-no-files-found: warn

      - name: Collect build result
        run: |
          echo "Build completed successfully. ✅" >> pr_results.txt

      - name: Push merged branch back to origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin merged

      - name: Comment on all PRs
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while read branch pr_number; do
            echo "Posting result to PR #$pr_number"
            COMMENT=$(grep "PR #$pr_number" pr_results.txt || echo "Your PR was part of a combined build. ✅")
            gh pr comment $pr_number --body ":robot: Combined Build Result on \`merged\` branch:\n$COMMENT"
          done < pr_branches.txt


